export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const RESET_ENTHUSIASM = 'RESET_ENTHUSIASM';
export type RESET_ENTHUSIASM = typeof RESET_ENTHUSIASM;

export const TEST = 'TEST';
export type TEST = typeof TEST;
